### ISSUE TITLE
Provide build scripts / instructions

### ISSUE THREAD

**Issue by voltagex** [therealsaumil/static-arm-bins#3]
This looks really cool - any chance you could document how these binaries were built?

**Comment by ricardojlrufino** [comment]
+1

**Comment by therealsaumil** [comment]
This collection of static binaries is provided as-is. Some of them are compiled by me, using the usual CFLAGS/LDFLAGS=-static incantations in the Makefiles; some contributed by friends, and some collected from the world wide web.
