### ISSUE TITLE
issue with ldd-arm-static

### ISSUE THREAD

**Issue by KiterSoze** [therealsaumil/static-arm-bins#8]
Hello,

Thanks you for your work, i have some issue with the ldd-arm-static command while the others are working fine.

Here is the error message:
```bash
$ ldd-arm-static
qemu-arm-static: Could not open '/lib/ld-uClibc.so.0': No such file or directory
```
 
if I badly "link" the libc, I get the following message.
```bash
$ ldd-arm-static
/ bin / ldd-arm-static: symbol lookup error: / bin / ldd-arm-static: undefined symbol: __uClibc_main
```

I hope I don't make a stupid mistake

```bash
sha256sum /bin/ldd-arm-static
ae30082165cdaddfc6e1a6c6a945062c9227e37e65422951d23517f7293c0143  /bin/ldd-arm-static
```

**Comment by therealsaumil** [comment]
I'm not sure of the running environment you are using. If you're running it within an ARM Linux system then it should work just fine. Here it looks like you're running it using some QEMU user mode emulation. I don't know what it's expected outcome should be.
